dependencies:
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.5
  flutter_riverpod: ^1.0.0
  fuzzywuzzy: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  hive_generator: ^1.0.0
  json_annotation: ^4.4.0
  path: ^1.8.2
  permission_handler: ^10.2.0
  star_menu: ^3.1.0+1
description: 'A trusty, strong and reliable application launcher for Android - because
  all others are crap.'
dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
environment:
  sdk: '>=2.18.1 <3.0.0'
flutter:
  assets:
    - images/spear.png
    - images/avatar.png
  uses-material-design: true
name: firmus
publish_to: none
version: 1.0.0+1
