dependencies:
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  fuzzywuzzy: ^0.2.0
  path: ^1.8.2
  permission_handler: ^10.2.0
  sqflite: ^2.1.0+1
description: 'A trusty, strong and reliable application launcher for Android - because
  all others are crap.'
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.1 <3.0.0'
flutter:
  assets:
    - images/spear.png
    - images/avatar.png
  uses-material-design: true
name: firmus
publish_to: none
version: 1.0.0+1
